### ISSUE TITLE
cannot import name 'find_targets' from metarna.pymiranda import find_targets

### ISSUE THREAD

**Issue by JinyuanSun** [PrashntS/pancake#12]
```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    from metarna.target_scan import scan, free_energy
  File "/data2/big_F/metaRNA/metarna/target_scan.py", line 3, in <module>
    from metarna.pymiranda import find_targets
ImportError: cannot import name 'find_targets'
```

**Comment by JinyuanSun** [comment]
sorry, ran `examply.py` in wrong dir.
